apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kubernetes-demo
  name: kubernetes-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-demo
  template:
    metadata:
      labels:
        app: kubernetes-demo
    spec:
      containers:
      - image: localhost:5000/kubernetes-demo/kubernetes-demo:latest
        name: kubernetes-demo
        imagePullPolicy: Always
