apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-demo
  name: http
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: kubernetes-demo
  type: NodePort
